package com.spring.jwt.db.maria.model.security;
// Generated Dec 12, 2018 10:15:59 AM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * AppCodes generated by hbm2java
 */
@Entity
@Table(name = "app_codes", uniqueConstraints = @UniqueConstraint(columnNames = { "app_name", "code_type",
		"code_value" }))
public class AppCodes implements java.io.Serializable {

	private long id;
	private String appName;
	private String codeType;
	private String codeValue;
	private String codeDesc;
	private String codeDescEng;
	private Date createDate;
	private Date updateDate;
	private Long createUser;
	private Long updateUser;

	public AppCodes() {
	}

	public AppCodes(long id, String appName, String codeType, String codeValue) {
		this.id = id;
		this.appName = appName;
		this.codeType = codeType;
		this.codeValue = codeValue;
	}

	public AppCodes(long id, String appName, String codeType, String codeValue, String codeDesc, String codeDescEng,
			Date createDate, Date updateDate, Long createUser, Long updateUser) {
		this.id = id;
		this.appName = appName;
		this.codeType = codeType;
		this.codeValue = codeValue;
		this.codeDesc = codeDesc;
		this.codeDescEng = codeDescEng;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.createUser = createUser;
		this.updateUser = updateUser;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "app_name", nullable = false, length = 100)
	public String getAppName() {
		return this.appName;
	}

	public void setAppName(String appName) {
		this.appName = appName;
	}

	@Column(name = "code_type", nullable = false, length = 50)
	public String getCodeType() {
		return this.codeType;
	}

	public void setCodeType(String codeType) {
		this.codeType = codeType;
	}

	@Column(name = "code_value", nullable = false, length = 100)
	public String getCodeValue() {
		return this.codeValue;
	}

	public void setCodeValue(String codeValue) {
		this.codeValue = codeValue;
	}

	@Column(name = "code_desc", length = 65535)
	public String getCodeDesc() {
		return this.codeDesc;
	}

	public void setCodeDesc(String codeDesc) {
		this.codeDesc = codeDesc;
	}

	@Column(name = "code_desc_eng", length = 65535)
	public String getCodeDescEng() {
		return this.codeDescEng;
	}

	public void setCodeDescEng(String codeDescEng) {
		this.codeDescEng = codeDescEng;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 26)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 26)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "create_user")
	public Long getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(Long createUser) {
		this.createUser = createUser;
	}

	@Column(name = "update_user")
	public Long getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(Long updateUser) {
		this.updateUser = updateUser;
	}

}
