package com.spring.jwt.db.maria.model.authentication;
// Generated Jul 12, 2018 3:28:17 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserAuthorityId generated by hbm2java
 */
@Embeddable
public class UserAuthorityId implements java.io.Serializable {

	private long userId;
	private long authorityId;

	public UserAuthorityId() {
	}

	public UserAuthorityId(long userId, long authorityId) {
		this.userId = userId;
		this.authorityId = authorityId;
	}

	@Column(name = "user_id", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "authority_id", nullable = false)
	public long getAuthorityId() {
		return this.authorityId;
	}

	public void setAuthorityId(long authorityId) {
		this.authorityId = authorityId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserAuthorityId))
			return false;
		UserAuthorityId castOther = (UserAuthorityId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getAuthorityId() == castOther.getAuthorityId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37 * result + (int) this.getAuthorityId();
		return result;
	}

}
